const resList = [
  {
    data: {
      id: "255655",
      name: "Cake & Cream",
  // Use a placeholder image for development
  cloudinaryImageId: "https://images.pexels.com/photos/262978/pexels-photo-262978.jpeg?_gl=1*uhl26f*_ga*MTQyMzk0NDgyMi4xNzYwMTU4NDU4*_ga_8JE65Q40S6*czE3NjAxNTg0NTgkbzEkZzAkdDE3NjAxNTg0NTgkajYwJGwwJGgw",
      areaName: "Jairaj Nagar",
      costForTwo: "₹200 for two",
      cuisines: ["Bakery", "Hot-dog", "Pastery", "Cake", "Thick-shake"],
      avgRating: 4.3,
      veg: true,
      parentId: "54670",
      avgRatingString: "4",
      totalRatingsString: "20+",
    },
  },
  {
    data: {
      id: "350363",
      name: "Haldiram's Sweets and Namkeen",
  cloudinaryImageId: "https://images.pexels.com/photos/34227767/pexels-photo-34227767.jpeg?_gl=1*1upaqkk*_ga*MTQyMzk0NDgyMi4xNzYwMTU4NDU4*_ga_8JE65Q40S6*czE3NjAxNTg0NTgkbzEkZzEkdDE3NjAxNTg3MDQkajYwJGwwJGgw",
      avgRating: 4.6,
      veg: true,
      cuisines: ["North Indian", "South Indian", "Chinese", "Pizzas", "Fast Food"],
      parentId: "391465",
      avgRatingString: "4.6",
      totalRatingsString: "100+",
    },
  },
  {
    data: {
      id: "154891",
      name: "Rasraj Restaurant",
  cloudinaryImageId: "https://images.pexels.com/photos/1482803/pexels-photo-1482803.jpeg?_gl=1*164718v*_ga*MTQyMzk0NDgyMi4xNzYwMTU4NDU4*_ga_8JE65Q40S6*czE3NjAxNTg0NTgkbzEkZzEkdDE3NjAxNTg2NDEkajU1JGwwJGgw",
      locality: "Civil Line",
      areaName: "Civil Lines",
      costForTwo: "₹250 for two",
      cuisines: ["North Indian", "South Indian", "Street Food", "Chinese", "Pizzas", "Fast Food"],
      avgRating: 4.2,
    },
  },
  {
    data: {
      id: "745961",
      name: "Balaji Restaurant",
  cloudinaryImageId: "https://images.pexels.com/photos/34227767/pexels-photo-34227767.jpeg?_gl=1*1upaqkk*_ga*MTQyMzk0NDgyMi4xNzYwMTU4NDU4*_ga_8JE65Q40S6*czE3NjAxNTg0NTgkbzEkZzEkdDE3NjAxNTg3MDQkajYwJGwwJGgw",
      locality: "Sai Rubber Stamp",
      areaName: "Jairaj Nagar",
      costForTwo: "₹149 for two",
      cuisines: ["South Indian", "North Indian"],
      avgRating: 4.8,
      veg: true,
    },
  },
  {
    data: {
      id: "798745",
      name: "Friends Restaurant",
  cloudinaryImageId: "https://images.pexels.com/photos/1482803/pexels-photo-1482803.jpeg?_gl=1*164718v*_ga*MTQyMzk0NDgyMi4xNzYwMTU4NDU4*_ga_8JE65Q40S6*czE3NjAxNTg0NTgkbzEkZzEkdDE3NjAxNTg2NDEkajU1JGwwJGgw",
      locality: "Gayatri Nagar",
      areaName: "Jairaj Nagar",
      costForTwo: "₹150 for two",
      cuisines: ["North Indian", "Chinese", "Biryani", "Tandoor", "Kebabs"],
      avgRating: 4.2,
      parentId: "84308",
    },
  },
  {
    data: {
      id: "314737",
      name: "RASOI the KITCHEN",
  cloudinaryImageId:"https://images.pexels.com/photos/1482803/pexels-photo-1482803.jpeg?_gl=1*164718v*_ga*MTQyMzk0NDgyMi4xNzYwMTU4NDU4*_ga_8JE65Q40S6*czE3NjAxNTg0NTgkbzEkZzEkdDE3NjAxNTg2NDEkajU1JGwwJGgw",
      locality: "Sriram Chowk",
      areaName: "Bazar Ward",
      costForTwo: "₹200 for two",
      cuisines: ["North Indian", "Maharashtrian", "Chinese", "Thalis"],
      avgRating: 3.9,
      parentId: "167341",
    },
  },
  {
    data: {
      id: "201454",
      name: "Morsels restaurants",
  cloudinaryImageId: "https://images.pexels.com/photos/34227767/pexels-photo-34227767.jpeg?_gl=1*1upaqkk*_ga*MTQyMzk0NDgyMi4xNzYwMTU4NDU4*_ga_8JE65Q40S6*czE3NjAxNTg0NTgkbzEkZzEkdDE3NjAxNTg3MDQkajYwJGwwJGgw",
      locality: "Bazar Ward",
      areaName: "Chandrapur Locality",
      costForTwo: "₹300 for two",
      cuisines: ["North Indian", "South Indian"],
      avgRating: 3.2,
      veg: true,
      parentId: "139266",
      avgRatingString: "4.2",
    },
  },
  {
    data: {
      id: "266124",
      name: "Trimurti Restaurant",
  cloudinaryImageId: "https://images.pexels.com/photos/1482803/pexels-photo-1482803.jpeg?_gl=1*164718v*_ga*MTQyMzk0NDgyMi4xNzYwMTU4NDU4*_ga_8JE65Q40S6*czE3NjAxNTg0NTgkbzEkZzEkdDE3NjAxNTg2NDEkajU1JGwwJGgw",
      locality: "Bazar Ward",
      areaName: "Chandrapur Locality",
      costForTwo: "₹150 for two",
      cuisines: ["Desserts"],
      avgRating: 3.9,
      veg: true,
      parentId: "217751",
      avgRatingString: "4.4",
    },
  },
  {
    data: {
      id: "509254",
      name: "Saha Restaurant",
  cloudinaryImageId: "https://images.pexels.com/photos/1482803/pexels-photo-1482803.jpeg?_gl=1*164718v*_ga*MTQyMzk0NDgyMi4xNzYwMTU4NDU4*_ga_8JE65Q40S6*czE3NjAxNTg0NTgkbzEkZzEkdDE3NjAxNTg2NDEkajU1JGwwJGgw",
      areaName: "Jairaj Nagar",
      costForTwo: "₹300 for two",
      cuisines: ["North Indian", "Biryani", "Thalis", "Beverages"],
      avgRating: 3.7,
      parentId: "174585",
      avgRatingString: "3.7",
    },
  },
];

export default resList;
